# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/HWSW/Documents/project_2/project_2.srcs/sources_1/bd/design_1/ip/design_1_my_axis_int_matp_cnt_0_0/design_1_my_axis_int_matp_cnt_0_0.xci
# IP: The module: 'design_1_my_axis_int_matp_cnt_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/Users/HWSW/Documents/project_2/project_2.srcs/sources_1/bd/design_1/ip/design_1_my_axis_int_matp_cnt_0_0/src/blk_mem_gen_0/blk_mem_gen_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==blk_mem_gen_0 || ORIG_REF_NAME==blk_mem_gen_0} -quiet] -quiet

# XDC: c:/Users/HWSW/Documents/project_2/project_2.srcs/sources_1/bd/design_1/ip/design_1_my_axis_int_matp_cnt_0_0/src/blk_mem_gen_0/blk_mem_gen_0_ooc.xdc

# IP: c:/Users/HWSW/Documents/project_2/project_2.srcs/sources_1/bd/design_1/ip/design_1_my_axis_int_matp_cnt_0_0/design_1_my_axis_int_matp_cnt_0_0.xci
# IP: The module: 'design_1_my_axis_int_matp_cnt_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/Users/HWSW/Documents/project_2/project_2.srcs/sources_1/bd/design_1/ip/design_1_my_axis_int_matp_cnt_0_0/src/blk_mem_gen_0/blk_mem_gen_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==blk_mem_gen_0 || ORIG_REF_NAME==blk_mem_gen_0} -quiet] -quiet

# XDC: c:/Users/HWSW/Documents/project_2/project_2.srcs/sources_1/bd/design_1/ip/design_1_my_axis_int_matp_cnt_0_0/src/blk_mem_gen_0/blk_mem_gen_0_ooc.xdc
